version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/aws"
    schedule:
      interval: "daily"

  - package-ecosystem: "terraform"
    directory: "/github"
    schedule:
      interval: "daily"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
