version: 2
updates:
  - package-ecosystem: "terraform"
    directory: "/aws"
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'

  - package-ecosystem: "terraform"
    directory: "/github"
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: monthly
    reviewers:
      - 'femiwiki/reviewer'
    ignore:
      - dependency-name: '*'
        update-types:
          - 'version-update:semver-minor'
          - 'version-update:semver-patch'
