name: femiwiki

services:
  http:
    image: ghcr.io/femiwiki/femiwiki:2025-05-24t17-47-df7f1357
    command: caddy run
    volumes:
      - type: bind
        source: /srv/femiwiki.com/Caddyfile
        target: /srv/femiwiki.com/Caddyfile
      - type: bind
        source: /srv/femiwiki.com/robots.txt
        target: /srv/femiwiki.com/robots.txt
      - type: bind
        source: /srv/femiwiki.com/sitemap
        target: /srv/femiwiki.com/sitemap
    environment:
      FASTCGI_ADDR: 127.0.0.1:9000
      AWS_REGION: ap-northeast-1
      S3_USE_IAM_PROVIDER: true
      S3_HOST: s3.ap-northeast-1.amazonaws.com
      S3_BUCKET: femiwiki-secrets
      S3_PREFIX: caddycerts
    deploy:
      restart_policy:
        condition: on-failure
        delay: 5s
        max_attempts: 3
        window: 120s
    network_mode: host
    restart: always
    depends_on:
      - fastcgi

  fastcgi:
    image: ghcr.io/femiwiki/femiwiki:2025-05-24t17-47-df7f1357
    volumes:
      - type: bind
        source: /a/secrets.php
        target: /a/secrets.php
      - type: bind
        source: /a/Hotfix.php
        target: /a/Hotfix.php
      - type: bind
        source: /a/analytics-credentials-file.json
        target: /a/analytics-credentials-file.json
      - type: bind
        source: /usr/local/etc/php/conf.d/opcache-recommended.ini
        target: /usr/local/etc/php/conf.d/opcache-recommended.ini
      - type: bind
        source: /usr/local/etc/php/php.ini
        target: /usr/local/etc/php/php.ini
      - type: bind
        source: /usr/local/etc/php-fpm.conf
        target: /usr/local/etc/php-fpm.conf
      - /tmp/cache:/tmp/cache
    environment:
      MEDIAWIKI_SKIP_IMPORT_SITES: '1'
      MEDIAWIKI_SKIP_INSTALL: '1'
      MEDIAWIKI_SKIP_UPDATE: '1'
      WG_CDN_SERVERS: 127.0.0.1:80
      WG_DB_SERVER: 127.0.0.1:3306
      WG_DB_USER: mediawiki
      DB_PASSWORD_FILE: /run/secrets/db_user_password
      WG_INTERNAL_SERVER: http://127.0.0.1:80
      WG_MEMCACHED_SERVERS: 127.0.0.1:11211
    secrets:
      - db_user_password
    depends_on:
      - mysql
      - memcached
    network_mode: host
    restart: always

  mysql:
    image: mysql/mysql-server:8.0.32
    volumes:
      - /srv/mysql:/srv/mysql
      - /etc/mysql:/etc/mysql
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    network_mode: host
    restart: always

  memcached:
    image: memcached:1.6.23-alpine
    network_mode: host
    restart: always

secrets:
  db_user_password:
    file: /a/db_user_password.txt
