# https://vector.dev/docs/reference/configuration/

[api]
enabled = true

[sources.vector_logs]
type = "internal_logs"

[transforms.vector_log_parser]
inputs = ["vector_logs"]
type = "remap"
source = '''
structured = {}

if is_string(.message) {
  structured.msg = .message
}
if is_string(.metadata.level) {
  structured.level = downcase!(.metadata.level)
}

.message = structured
'''

[sources.docker_logs]
type = "docker_logs"

[transforms.docker_json_parser]
inputs = ["docker_logs"]
type = "remap"
source = '''
del(.container_created_at)
if is_string(.image) && contains(string!(.image), ":") {
  .image_repository = split(string!(.image), r':')[0]
}

if is_json(string!(.message)) {
  .message.msg = parse_json!(string!(.message))
} else if is_string(.message) {
  .message = {"msg": .message}
}
'''

[sinks.openobserve]
type = "http"
inputs = [
  "vector_log_parser",
  "docker_json_parser",
]
uri = "https://api.openobserve.ai/api/femiwiki_2lbGLNGsIgcwF9Y/default/_json"
method = "post"
auth.strategy = "basic"
auth.user = "admin@femiwiki.com"
auth.password = "OPENOBSERVE_PASSWORD"
compression = "gzip"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = false
