# https://vector.dev/docs/reference/configuration/

[api]
enabled = true

[sources.vector_logs]
type = "internal_logs"

[sinks.openobserve_vector_logs]
type = "http"
inputs = ["vector_logs"]
uri = "https://api.openobserve.ai/api/femiwiki_2lbGLNGsIgcwF9Y/vector_logs/_json"
method = "post"
auth.strategy = "basic"
auth.user = "admin@femiwiki.com"
auth.password = "OPENOBSERVE_PASSWORD"
compression = "gzip"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = false

[sources.docker_logs]
type = "docker_logs"

[transforms.docker_json_parser]
inputs = ["docker_logs"]
type = "remap"
source = '''
if is_string(.image) && contains(string!(.image), ":") {
  .image_repository = split(string!(.image), r':')[0]
}

if is_json(string!(.message)) {
  .message.msg = parse_json!(string!(.message))
} else if is_string(.message) {
  .message = {"msg": .message}
}
'''

[sinks.openobserve_docker_logs]
type = "http"
inputs = ["docker_json_parser",]
uri = "https://api.openobserve.ai/api/femiwiki_2lbGLNGsIgcwF9Y/docker_logs/_json"
method = "post"
auth.strategy = "basic"
auth.user = "admin@femiwiki.com"
auth.password = "OPENOBSERVE_PASSWORD"
compression = "gzip"
encoding.codec = "json"
encoding.timestamp_format = "rfc3339"
healthcheck.enabled = false
