name: Digger Workflow

on:
  workflow_dispatch:
    inputs:
      run_name:
        required: false
      spec:
        required: true

run-name: '${{inputs.run_name}}'

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write      # required to merge PRs
      id-token: write      # required for workload-identity-federation
      pull-requests: write # required to post PR comments
      issues: read         # required to check if PR number is an issue or not
      statuses: write      # required to validate combined PR status

    steps:
      - uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.5"
          cli_config_credentials_token: ${{ secrets.TF_API_TOKEN }}
      - name: digger run
        uses: diggerhq/digger@vLatest
        with:
          digger-spec: ${{ inputs.spec }}
          setup-aws: true
          aws-role-to-assume: arn:aws:iam::302617221463:role/digger
          aws-region: ap-northeast-1
          cache-dependencies: true
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
