---
name: docker apply
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
permissions: {}
concurrency:
  group: docker
jobs:
  apply:
    uses: ./.github/workflows/tofu-apply.yaml
    permissions:
      actions: write
      contents: read
      id-token: write
      pull-requests: write
    with:
      workspace: docker
      ssm_docker_tunnel: true
      timeout_minutes: 20
    secrets:
      status_webhook: ${{ secrets.DOCKER_DISCORD_WEBHOOK }}
