name: CI

on: [push, pull_request]

jobs:
  format:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    - name: Validate
      run: terraform validate
    - name: Format
      run: terraform fmt -check -diff -recursive
