name: CI

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Validate
      run: terraform validate
    - name: Format
      run: terraform fmt -check -diff -recursive
