---
name: grafana apply
on:
  issue_comment:
    types: [created]
  workflow_dispatch:
permissions: {}
concurrency:
  group: grafana
jobs:
  apply:
    uses: ./.github/workflows/tofu-apply.yaml
    permissions:
      actions: write
      contents: read
      id-token: write
      pull-requests: write
    with:
      workspace: grafana
    secrets:
      status_webhook: ${{ secrets.GRAFANA_DISCORD_WEBHOOK }}
      grafana_auth: ${{ secrets.GRAFANA_APPLY_TOKEN }}
      discord_webhook_url: ${{ secrets.DISCORD_WEBHOOK_URL }}
